export const SYMBOL_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const SYMBOL_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const SYMBOL_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const SYMBOL_CREATE_RESET = "ORDER_CREATE_RESET";

export const SYMBOL_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const SYMBOL_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const SYMBOL_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const SYMBOL_UPDATE_RESET = "ORDER_UPDATE_RESET";

export const SYMBOL_LIST_REQUEST = "ORDER_DETAILS_REQUEST";
export const SYMBOL_LIST_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const SYMBOL_LIST_FAIL = "ORDER_DETAILS_FAIL";

export const SYMBOL_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const SYMBOL_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const SYMBOL_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const SYMBOL_DELETE_RESET = "ORDER_DELETE_RESET";

export const POSITION_LIST_REQUEST = "ORDER_DETAILS_REQUEST";
export const POSITION_LIST_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const POSITION_LIST_FAIL = "ORDER_DETAILS_FAIL";
